### ISSUE TITLE
error with create_semantic_index.py example

### ISSUE THREAD

**Issue by KonradHoeffner** [Ayuei/DeBEIR#11]
```
(venv) indexing$ python create_semantic_index.py 
2023-02-28 13:35:37.990490: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 13:35:38.071820: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-28 13:35:38.074573: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-28 13:35:38.074588: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-28 13:35:38.595994: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-28 13:35:38.596048: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-28 13:35:38.596056: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/konrad/tmp/debeir/examples/indexing/create_semantic_index.py", line 81, in <module>
    raise e
  File "/home/konrad/tmp/debeir/examples/indexing/create_semantic_index.py", line 79, in <module>
    plac.call(main)
  File "/home/konrad/.local/lib/python3.10/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/home/konrad/.local/lib/python3.10/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/konrad/tmp/debeir/examples/indexing/create_semantic_index.py", line 40, in main
    config = config_factory(config, GenericConfig)
  File "/home/konrad/.local/lib/python3.10/site-packages/debeir/datasets/factory.py", line 119, in config_factory
    return config_cls.from_args(args_dict, config_cls)
  File "/home/konrad/.local/lib/python3.10/site-packages/debeir/core/config.py", line 62, in from_args
    obj = field_class(**{k: v for k, v in args_dict.items() if k in field_names})
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by Ayuei** [comment]
This requires a bit of setup to get working. 

I added a [README.md](https://github.com/Ayuei/DeBEIR/blob/main/examples/indexing/README.md) with some instructions, which I think should solve this issue.
